### ISSUE TITLE
"application data after close notify" error caused by aiohttp

### ISSUE THREAD

**Issue by NaviTheCoderboi** [FallenDeity/PokeLance#1]
I am using Pokelance with my own aiohttp client session to make a guess the pokemon game 
But i get this error when i try to get ping of api
![IMG_20230402_121641](https://user-images.githubusercontent.com/102732282/229337346-6b1bfb81-fac5-4679-8455-4547d8e3bde4.jpg)

This is my code
```python
async def get_rand_poke():
	rand_poke = random.randint(1,1008)
	async with aiohttp.ClientSession() as session, pk.PokeLance(session=session) as client:
		print(await client.ping())

@bot.command()
async def wtp(self):
    c = await get_rand_poke()
```

**Comment by FallenDeity** [comment]
Seems to mainly be an elusive issue with internet i am guessing due to replit
https://github.com/aio-libs/aiohttp/issues/3477#issuecomment-466715832

above issue has been referenced before try re running the script also fyi u could do something like this

```py
import random

import discord
from pokelance import PokeLance
from.discord.ext import commands


bot = commands.Bot(command_prefix=".", intents=discord.Intents.all())

async def setup_hook():
    bot.http_session = aiohttp.ClientSession()
    bot.pokelance = PokeLance(session=bot.http_session)
    print(await bot.pokelance.ping())

bot.setup_hook = setup_hook

@bot.command()
async def random_pokemon(ctx: commands.Context) -> None:
    pokemon = random.choice(list(bot.pokelance.pokemon.cache.pokemon.endpoints.keys()))
    print(await bot.pokelance.pokemon.fetch_pokemon(pokemon))
```

**Comment by NaviTheCoderboi** [comment]
Whats difference between your code and mine i sent? 
@FallenDeity

**Comment by NaviTheCoderboi** [comment]
Ok, I tried your code and it worked 
Thanks tho
